spring:
  datasource:
    url: jdbc:mysql://192.168.0.77:3307/hyanzz?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: adpopo1234
    driver-class-name: com.mysql.cj.jdbc.Driver


#自定义配置文件
custom:
  configs:
    config: classpath:config/config-dev.yml